"""Auto-generated by `gli specifications generate-builtin-classes --version v4_4_1`. Do not edit by hand."""

from __future__ import annotations

from pydantic import BaseModel


class Colorv4_4_1(BaseModel):
    r: float
    g: float
    b: float
    a: float
    r8: int
    g8: int
    b8: int
    a8: int
    h: float
    s: float
    v: float
    ok_hsl_h: float
    ok_hsl_s: float
    ok_hsl_l: float


class Quaternionv4_4_1(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Vector2v4_4_1(BaseModel):
    x: float
    y: float


class Vector2iv4_4_1(BaseModel):
    x: int
    y: int


class Vector3v4_4_1(BaseModel):
    x: float
    y: float
    z: float


class Vector3iv4_4_1(BaseModel):
    x: int
    y: int
    z: int


class Vector4v4_4_1(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Vector4iv4_4_1(BaseModel):
    x: int
    y: int
    z: int
    w: int


class AABBv4_4_1(BaseModel):
    position: Vector3v4_4_1
    size: Vector3v4_4_1
    end: Vector3v4_4_1


class Basisv4_4_1(BaseModel):
    x: Vector3v4_4_1
    y: Vector3v4_4_1
    z: Vector3v4_4_1


class Planev4_4_1(BaseModel):
    x: float
    y: float
    z: float
    d: float
    normal: Vector3v4_4_1


class Projectionv4_4_1(BaseModel):
    x: Vector4v4_4_1
    y: Vector4v4_4_1
    z: Vector4v4_4_1
    w: Vector4v4_4_1


class Rect2v4_4_1(BaseModel):
    position: Vector2v4_4_1
    size: Vector2v4_4_1
    end: Vector2v4_4_1


class Rect2iv4_4_1(BaseModel):
    position: Vector2iv4_4_1
    size: Vector2iv4_4_1
    end: Vector2iv4_4_1


class Transform2Dv4_4_1(BaseModel):
    x: Vector2v4_4_1
    y: Vector2v4_4_1
    origin: Vector2v4_4_1


class Transform3Dv4_4_1(BaseModel):
    basis: Basisv4_4_1
    origin: Vector3v4_4_1
