"""Auto-generated by `gli specifications generate-builtin-classes`. Do not edit by hand."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class GodotConstant:
    class_name: str
    name: str
    type: str
    raw_value: str


BY_GODOT_NAME = {}
