"""Auto-generated by `gli specifications generate-signals --version v4_4_0`. Do not edit by hand."""

from __future__ import annotations

from typing import Dict, Tuple

from pydantic import BaseModel, ConfigDict


class SignalArgument(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    type: str


class GodotSignal(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    arguments: Tuple[SignalArgument, ...] = ()


SIGNALS: Dict[str, Dict[str, GodotSignal]] = {}
