"""Auto-generated by `gli specifications sync-schemas-v4-7-0`. Do not edit by hand."""

from __future__ import annotations

from enum import Enum
from typing import Union


class GodotTypeNameEnum(str, Enum):
    """Name of a Godot variant/builtin type, as it shows up across return types, argument types, etc."""

    AABB = "AABB"
    ARRAY = "Array"
    BASIS = "Basis"
    CALLABLE = "Callable"
    COLOR = "Color"
    DICTIONARY = "Dictionary"
    NODE_PATH = "NodePath"
    OBJECT = "Object"
    PACKED_BYTE_ARRAY = "PackedByteArray"
    PACKED_COLOR_ARRAY = "PackedColorArray"
    PACKED_FLOAT32_ARRAY = "PackedFloat32Array"
    PACKED_FLOAT64_ARRAY = "PackedFloat64Array"
    PACKED_INT32_ARRAY = "PackedInt32Array"
    PACKED_INT64_ARRAY = "PackedInt64Array"
    PACKED_STRING_ARRAY = "PackedStringArray"
    PACKED_VECTOR2_ARRAY = "PackedVector2Array"
    PACKED_VECTOR3_ARRAY = "PackedVector3Array"
    PACKED_VECTOR4_ARRAY = "PackedVector4Array"
    PLANE = "Plane"
    PROJECTION = "Projection"
    QUATERNION = "Quaternion"
    RID = "RID"
    RECT2 = "Rect2"
    RECT2I = "Rect2i"
    SIGNAL = "Signal"
    STRING = "String"
    STRING_NAME = "StringName"
    TRANSFORM2D = "Transform2D"
    TRANSFORM3D = "Transform3D"
    VARIANT = "Variant"
    VECTOR2 = "Vector2"
    VECTOR2I = "Vector2i"
    VECTOR3 = "Vector3"
    VECTOR3I = "Vector3i"
    VECTOR4 = "Vector4"
    VECTOR4I = "Vector4i"
    BOOL = "bool"
    FLOAT = "float"
    INT = "int"


GodotTypeName = Union[GodotTypeNameEnum, str]

UtilityFunctionReturnType = GodotTypeName


class UtilityFunctionCategoryEnum(str, Enum):
    GENERAL = "general"
    MATH = "math"
    RANDOM = "random"


UtilityFunctionCategory = Union[UtilityFunctionCategoryEnum, str]


class BuiltinClassOperatorNameEnum(str, Enum):
    NOT_EQUAL = "!="
    MODULO = "%"
    BIT_AND = "&"
    MULTIPLY = "*"
    POWER = "**"
    ADD = "+"
    SUBTRACT = "-"
    DIVIDE = "/"
    LESS = "<"
    SHIFT_LEFT = "<<"
    LESS_EQUAL = "<="
    EQUAL = "=="
    GREATER = ">"
    GREATER_EQUAL = ">="
    SHIFT_RIGHT = ">>"
    BIT_XOR = "^"
    AND = "and"
    IN = "in"
    NOT = "not"
    OR = "or"
    UNARY_PLUS = "unary+"
    UNARY_MINUS = "unary-"
    XOR = "xor"
    BIT_OR = "|"
    BIT_NOT = "~"


BuiltinClassOperatorName = Union[BuiltinClassOperatorNameEnum, str]


class GodotArgumentMetaEnum(str, Enum):
    """Native C++ type refinement of an argument/return value, e.g. 'int64', 'double', 'uint8'."""

    CHAR32 = "char32"
    DOUBLE = "double"
    FLOAT = "float"
    INT16 = "int16"
    INT32 = "int32"
    INT64 = "int64"
    INT8 = "int8"
    REQUIRED = "required"
    UINT16 = "uint16"
    UINT32 = "uint32"
    UINT64 = "uint64"
    UINT8 = "uint8"


GodotArgumentMeta = Union[GodotArgumentMetaEnum, str]


class ClassApiTypeEnum(str, Enum):
    CORE = "core"
    EDITOR = "editor"


ClassApiType = Union[ClassApiTypeEnum, str]
