"""Auto-generated by `gli specifications generate-builtin-classes --version v4_5_0`. Do not edit by hand."""

from __future__ import annotations

from pydantic import BaseModel


class Colorv4_5_0(BaseModel):
    r: float
    g: float
    b: float
    a: float
    r8: int
    g8: int
    b8: int
    a8: int
    h: float
    s: float
    v: float
    ok_hsl_h: float
    ok_hsl_s: float
    ok_hsl_l: float


class Quaternionv4_5_0(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Vector2v4_5_0(BaseModel):
    x: float
    y: float


class Vector2iv4_5_0(BaseModel):
    x: int
    y: int


class Vector3v4_5_0(BaseModel):
    x: float
    y: float
    z: float


class Vector3iv4_5_0(BaseModel):
    x: int
    y: int
    z: int


class Vector4v4_5_0(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Vector4iv4_5_0(BaseModel):
    x: int
    y: int
    z: int
    w: int


class AABBv4_5_0(BaseModel):
    position: Vector3v4_5_0
    size: Vector3v4_5_0
    end: Vector3v4_5_0


class Basisv4_5_0(BaseModel):
    x: Vector3v4_5_0
    y: Vector3v4_5_0
    z: Vector3v4_5_0


class Planev4_5_0(BaseModel):
    x: float
    y: float
    z: float
    d: float
    normal: Vector3v4_5_0


class Projectionv4_5_0(BaseModel):
    x: Vector4v4_5_0
    y: Vector4v4_5_0
    z: Vector4v4_5_0
    w: Vector4v4_5_0


class Rect2v4_5_0(BaseModel):
    position: Vector2v4_5_0
    size: Vector2v4_5_0
    end: Vector2v4_5_0


class Rect2iv4_5_0(BaseModel):
    position: Vector2iv4_5_0
    size: Vector2iv4_5_0
    end: Vector2iv4_5_0


class Transform2Dv4_5_0(BaseModel):
    x: Vector2v4_5_0
    y: Vector2v4_5_0
    origin: Vector2v4_5_0


class Transform3Dv4_5_0(BaseModel):
    basis: Basisv4_5_0
    origin: Vector3v4_5_0
