"""Auto-generated by `gli specifications generate-signals --version v4_5_0`. Do not edit by hand."""

from __future__ import annotations

from typing import Dict, Tuple

from pydantic import BaseModel, ConfigDict


class SignalArgument(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    type: str


class GodotSignal(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    arguments: Tuple[SignalArgument, ...] = ()


SIGNALS: Dict[str, Dict[str, GodotSignal]] = {
    "AcceptDialog": {
        "canceled": GodotSignal(name="canceled"),
        "confirmed": GodotSignal(name="confirmed"),
        "custom_action": GodotSignal(
            name="custom_action",
            arguments=(SignalArgument(name="action", type="StringName"),),
        ),
    },
    "AnimatedSprite2D": {
        "animation_changed": GodotSignal(name="animation_changed"),
        "animation_finished": GodotSignal(name="animation_finished"),
        "animation_looped": GodotSignal(name="animation_looped"),
        "frame_changed": GodotSignal(name="frame_changed"),
        "sprite_frames_changed": GodotSignal(name="sprite_frames_changed"),
    },
    "AnimatedSprite3D": {
        "animation_changed": GodotSignal(name="animation_changed"),
        "animation_finished": GodotSignal(name="animation_finished"),
        "animation_looped": GodotSignal(name="animation_looped"),
        "frame_changed": GodotSignal(name="frame_changed"),
        "sprite_frames_changed": GodotSignal(name="sprite_frames_changed"),
    },
    "AnimationLibrary": {
        "animation_added": GodotSignal(
            name="animation_added",
            arguments=(SignalArgument(name="name", type="StringName"),),
        ),
        "animation_changed": GodotSignal(
            name="animation_changed",
            arguments=(SignalArgument(name="name", type="StringName"),),
        ),
        "animation_removed": GodotSignal(
            name="animation_removed",
            arguments=(SignalArgument(name="name", type="StringName"),),
        ),
        "animation_renamed": GodotSignal(
            name="animation_renamed",
            arguments=(
                SignalArgument(name="name", type="StringName"),
                SignalArgument(name="to_name", type="StringName"),
            ),
        ),
    },
    "AnimationMixer": {
        "animation_finished": GodotSignal(
            name="animation_finished",
            arguments=(SignalArgument(name="anim_name", type="StringName"),),
        ),
        "animation_libraries_updated": GodotSignal(name="animation_libraries_updated"),
        "animation_list_changed": GodotSignal(name="animation_list_changed"),
        "animation_started": GodotSignal(
            name="animation_started",
            arguments=(SignalArgument(name="anim_name", type="StringName"),),
        ),
        "caches_cleared": GodotSignal(name="caches_cleared"),
        "mixer_applied": GodotSignal(name="mixer_applied"),
        "mixer_updated": GodotSignal(name="mixer_updated"),
    },
    "AnimationNode": {
        "animation_node_removed": GodotSignal(
            name="animation_node_removed",
            arguments=(
                SignalArgument(name="object_id", type="int"),
                SignalArgument(name="name", type="String"),
            ),
        ),
        "animation_node_renamed": GodotSignal(
            name="animation_node_renamed",
            arguments=(
                SignalArgument(name="object_id", type="int"),
                SignalArgument(name="old_name", type="String"),
                SignalArgument(name="new_name", type="String"),
            ),
        ),
        "tree_changed": GodotSignal(name="tree_changed"),
    },
    "AnimationNodeBlendSpace2D": {
        "triangles_updated": GodotSignal(name="triangles_updated"),
    },
    "AnimationNodeBlendTree": {
        "node_changed": GodotSignal(
            name="node_changed",
            arguments=(SignalArgument(name="node_name", type="StringName"),),
        ),
    },
    "AnimationNodeStateMachinePlayback": {
        "state_finished": GodotSignal(
            name="state_finished",
            arguments=(SignalArgument(name="state", type="StringName"),),
        ),
        "state_started": GodotSignal(
            name="state_started",
            arguments=(SignalArgument(name="state", type="StringName"),),
        ),
    },
    "AnimationNodeStateMachineTransition": {
        "advance_condition_changed": GodotSignal(name="advance_condition_changed"),
    },
    "AnimationPlayer": {
        "animation_changed": GodotSignal(
            name="animation_changed",
            arguments=(
                SignalArgument(name="old_name", type="StringName"),
                SignalArgument(name="new_name", type="StringName"),
            ),
        ),
        "current_animation_changed": GodotSignal(
            name="current_animation_changed",
            arguments=(SignalArgument(name="name", type="String"),),
        ),
    },
    "AnimationTree": {
        "animation_player_changed": GodotSignal(name="animation_player_changed"),
    },
    "Area2D": {
        "area_entered": GodotSignal(
            name="area_entered", arguments=(SignalArgument(name="area", type="Area2D"),)
        ),
        "area_exited": GodotSignal(
            name="area_exited", arguments=(SignalArgument(name="area", type="Area2D"),)
        ),
        "area_shape_entered": GodotSignal(
            name="area_shape_entered",
            arguments=(
                SignalArgument(name="area_rid", type="RID"),
                SignalArgument(name="area", type="Area2D"),
                SignalArgument(name="area_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "area_shape_exited": GodotSignal(
            name="area_shape_exited",
            arguments=(
                SignalArgument(name="area_rid", type="RID"),
                SignalArgument(name="area", type="Area2D"),
                SignalArgument(name="area_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_entered": GodotSignal(
            name="body_entered", arguments=(SignalArgument(name="body", type="Node2D"),)
        ),
        "body_exited": GodotSignal(
            name="body_exited", arguments=(SignalArgument(name="body", type="Node2D"),)
        ),
        "body_shape_entered": GodotSignal(
            name="body_shape_entered",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node2D"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_shape_exited": GodotSignal(
            name="body_shape_exited",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node2D"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
    },
    "Area3D": {
        "area_entered": GodotSignal(
            name="area_entered", arguments=(SignalArgument(name="area", type="Area3D"),)
        ),
        "area_exited": GodotSignal(
            name="area_exited", arguments=(SignalArgument(name="area", type="Area3D"),)
        ),
        "area_shape_entered": GodotSignal(
            name="area_shape_entered",
            arguments=(
                SignalArgument(name="area_rid", type="RID"),
                SignalArgument(name="area", type="Area3D"),
                SignalArgument(name="area_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "area_shape_exited": GodotSignal(
            name="area_shape_exited",
            arguments=(
                SignalArgument(name="area_rid", type="RID"),
                SignalArgument(name="area", type="Area3D"),
                SignalArgument(name="area_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_entered": GodotSignal(
            name="body_entered", arguments=(SignalArgument(name="body", type="Node3D"),)
        ),
        "body_exited": GodotSignal(
            name="body_exited", arguments=(SignalArgument(name="body", type="Node3D"),)
        ),
        "body_shape_entered": GodotSignal(
            name="body_shape_entered",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node3D"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_shape_exited": GodotSignal(
            name="body_shape_exited",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node3D"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
    },
    "AudioServer": {
        "bus_layout_changed": GodotSignal(name="bus_layout_changed"),
        "bus_renamed": GodotSignal(
            name="bus_renamed",
            arguments=(
                SignalArgument(name="bus_index", type="int"),
                SignalArgument(name="old_name", type="StringName"),
                SignalArgument(name="new_name", type="StringName"),
            ),
        ),
    },
    "AudioStream": {
        "parameter_list_changed": GodotSignal(name="parameter_list_changed"),
    },
    "AudioStreamPlayer": {
        "finished": GodotSignal(name="finished"),
    },
    "AudioStreamPlayer2D": {
        "finished": GodotSignal(name="finished"),
    },
    "AudioStreamPlayer3D": {
        "finished": GodotSignal(name="finished"),
    },
    "BaseButton": {
        "button_down": GodotSignal(name="button_down"),
        "button_up": GodotSignal(name="button_up"),
        "pressed": GodotSignal(name="pressed"),
        "toggled": GodotSignal(
            name="toggled", arguments=(SignalArgument(name="toggled_on", type="bool"),)
        ),
    },
    "BoneMap": {
        "bone_map_updated": GodotSignal(name="bone_map_updated"),
        "profile_updated": GodotSignal(name="profile_updated"),
    },
    "ButtonGroup": {
        "pressed": GodotSignal(
            name="pressed",
            arguments=(SignalArgument(name="button", type="BaseButton"),),
        ),
    },
    "CPUParticles2D": {
        "finished": GodotSignal(name="finished"),
    },
    "CPUParticles3D": {
        "finished": GodotSignal(name="finished"),
    },
    "CameraFeed": {
        "format_changed": GodotSignal(name="format_changed"),
        "frame_changed": GodotSignal(name="frame_changed"),
    },
    "CameraServer": {
        "camera_feed_added": GodotSignal(
            name="camera_feed_added", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "camera_feed_removed": GodotSignal(
            name="camera_feed_removed",
            arguments=(SignalArgument(name="id", type="int"),),
        ),
        "camera_feeds_updated": GodotSignal(name="camera_feeds_updated"),
    },
    "CanvasItem": {
        "draw": GodotSignal(name="draw"),
        "hidden": GodotSignal(name="hidden"),
        "item_rect_changed": GodotSignal(name="item_rect_changed"),
        "visibility_changed": GodotSignal(name="visibility_changed"),
    },
    "CanvasLayer": {
        "visibility_changed": GodotSignal(name="visibility_changed"),
    },
    "CodeEdit": {
        "breakpoint_toggled": GodotSignal(
            name="breakpoint_toggled",
            arguments=(SignalArgument(name="line", type="int"),),
        ),
        "code_completion_requested": GodotSignal(name="code_completion_requested"),
        "symbol_hovered": GodotSignal(
            name="symbol_hovered",
            arguments=(
                SignalArgument(name="symbol", type="String"),
                SignalArgument(name="line", type="int"),
                SignalArgument(name="column", type="int"),
            ),
        ),
        "symbol_lookup": GodotSignal(
            name="symbol_lookup",
            arguments=(
                SignalArgument(name="symbol", type="String"),
                SignalArgument(name="line", type="int"),
                SignalArgument(name="column", type="int"),
            ),
        ),
        "symbol_validate": GodotSignal(
            name="symbol_validate",
            arguments=(SignalArgument(name="symbol", type="String"),),
        ),
    },
    "CollisionObject2D": {
        "input_event": GodotSignal(
            name="input_event",
            arguments=(
                SignalArgument(name="viewport", type="Node"),
                SignalArgument(name="event", type="InputEvent"),
                SignalArgument(name="shape_idx", type="int"),
            ),
        ),
        "mouse_entered": GodotSignal(name="mouse_entered"),
        "mouse_exited": GodotSignal(name="mouse_exited"),
        "mouse_shape_entered": GodotSignal(
            name="mouse_shape_entered",
            arguments=(SignalArgument(name="shape_idx", type="int"),),
        ),
        "mouse_shape_exited": GodotSignal(
            name="mouse_shape_exited",
            arguments=(SignalArgument(name="shape_idx", type="int"),),
        ),
    },
    "CollisionObject3D": {
        "input_event": GodotSignal(
            name="input_event",
            arguments=(
                SignalArgument(name="camera", type="Node"),
                SignalArgument(name="event", type="InputEvent"),
                SignalArgument(name="event_position", type="Vector3"),
                SignalArgument(name="normal", type="Vector3"),
                SignalArgument(name="shape_idx", type="int"),
            ),
        ),
        "mouse_entered": GodotSignal(name="mouse_entered"),
        "mouse_exited": GodotSignal(name="mouse_exited"),
    },
    "ColorPicker": {
        "color_changed": GodotSignal(
            name="color_changed",
            arguments=(SignalArgument(name="color", type="Color"),),
        ),
        "preset_added": GodotSignal(
            name="preset_added", arguments=(SignalArgument(name="color", type="Color"),)
        ),
        "preset_removed": GodotSignal(
            name="preset_removed",
            arguments=(SignalArgument(name="color", type="Color"),),
        ),
    },
    "ColorPickerButton": {
        "color_changed": GodotSignal(
            name="color_changed",
            arguments=(SignalArgument(name="color", type="Color"),),
        ),
        "picker_created": GodotSignal(name="picker_created"),
        "popup_closed": GodotSignal(name="popup_closed"),
    },
    "Container": {
        "pre_sort_children": GodotSignal(name="pre_sort_children"),
        "sort_children": GodotSignal(name="sort_children"),
    },
    "Control": {
        "focus_entered": GodotSignal(name="focus_entered"),
        "focus_exited": GodotSignal(name="focus_exited"),
        "gui_input": GodotSignal(
            name="gui_input",
            arguments=(SignalArgument(name="event", type="InputEvent"),),
        ),
        "minimum_size_changed": GodotSignal(name="minimum_size_changed"),
        "mouse_entered": GodotSignal(name="mouse_entered"),
        "mouse_exited": GodotSignal(name="mouse_exited"),
        "resized": GodotSignal(name="resized"),
        "size_flags_changed": GodotSignal(name="size_flags_changed"),
        "theme_changed": GodotSignal(name="theme_changed"),
    },
    "Curve": {
        "domain_changed": GodotSignal(name="domain_changed"),
        "range_changed": GodotSignal(name="range_changed"),
    },
    "EditorDebuggerSession": {
        "breaked": GodotSignal(
            name="breaked", arguments=(SignalArgument(name="can_debug", type="bool"),)
        ),
        "continued": GodotSignal(name="continued"),
        "started": GodotSignal(name="started"),
        "stopped": GodotSignal(name="stopped"),
    },
    "EditorFileDialog": {
        "dir_selected": GodotSignal(
            name="dir_selected", arguments=(SignalArgument(name="dir", type="String"),)
        ),
        "file_selected": GodotSignal(
            name="file_selected",
            arguments=(SignalArgument(name="path", type="String"),),
        ),
        "filename_filter_changed": GodotSignal(
            name="filename_filter_changed",
            arguments=(SignalArgument(name="filter", type="String"),),
        ),
        "files_selected": GodotSignal(
            name="files_selected",
            arguments=(SignalArgument(name="paths", type="PackedStringArray"),),
        ),
    },
    "EditorFileSystem": {
        "filesystem_changed": GodotSignal(name="filesystem_changed"),
        "resources_reimported": GodotSignal(
            name="resources_reimported",
            arguments=(SignalArgument(name="resources", type="PackedStringArray"),),
        ),
        "resources_reimporting": GodotSignal(
            name="resources_reimporting",
            arguments=(SignalArgument(name="resources", type="PackedStringArray"),),
        ),
        "resources_reload": GodotSignal(
            name="resources_reload",
            arguments=(SignalArgument(name="resources", type="PackedStringArray"),),
        ),
        "script_classes_updated": GodotSignal(name="script_classes_updated"),
        "sources_changed": GodotSignal(
            name="sources_changed",
            arguments=(SignalArgument(name="exist", type="bool"),),
        ),
    },
    "EditorInspector": {
        "edited_object_changed": GodotSignal(name="edited_object_changed"),
        "object_id_selected": GodotSignal(
            name="object_id_selected",
            arguments=(SignalArgument(name="id", type="int"),),
        ),
        "property_deleted": GodotSignal(
            name="property_deleted",
            arguments=(SignalArgument(name="property", type="String"),),
        ),
        "property_edited": GodotSignal(
            name="property_edited",
            arguments=(SignalArgument(name="property", type="String"),),
        ),
        "property_keyed": GodotSignal(
            name="property_keyed",
            arguments=(
                SignalArgument(name="property", type="String"),
                SignalArgument(name="value", type="Variant"),
                SignalArgument(name="advance", type="bool"),
            ),
        ),
        "property_selected": GodotSignal(
            name="property_selected",
            arguments=(SignalArgument(name="property", type="String"),),
        ),
        "property_toggled": GodotSignal(
            name="property_toggled",
            arguments=(
                SignalArgument(name="property", type="String"),
                SignalArgument(name="checked", type="bool"),
            ),
        ),
        "resource_selected": GodotSignal(
            name="resource_selected",
            arguments=(
                SignalArgument(name="resource", type="Resource"),
                SignalArgument(name="path", type="String"),
            ),
        ),
        "restart_requested": GodotSignal(name="restart_requested"),
    },
    "EditorPlugin": {
        "main_screen_changed": GodotSignal(
            name="main_screen_changed",
            arguments=(SignalArgument(name="screen_name", type="String"),),
        ),
        "project_settings_changed": GodotSignal(name="project_settings_changed"),
        "resource_saved": GodotSignal(
            name="resource_saved",
            arguments=(SignalArgument(name="resource", type="Resource"),),
        ),
        "scene_changed": GodotSignal(
            name="scene_changed",
            arguments=(SignalArgument(name="scene_root", type="Node"),),
        ),
        "scene_closed": GodotSignal(
            name="scene_closed",
            arguments=(SignalArgument(name="filepath", type="String"),),
        ),
        "scene_saved": GodotSignal(
            name="scene_saved",
            arguments=(SignalArgument(name="filepath", type="String"),),
        ),
    },
    "EditorProperty": {
        "multiple_properties_changed": GodotSignal(
            name="multiple_properties_changed",
            arguments=(
                SignalArgument(name="properties", type="PackedStringArray"),
                SignalArgument(name="value", type="Array"),
            ),
        ),
        "object_id_selected": GodotSignal(
            name="object_id_selected",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="id", type="int"),
            ),
        ),
        "property_can_revert_changed": GodotSignal(
            name="property_can_revert_changed",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="can_revert", type="bool"),
            ),
        ),
        "property_changed": GodotSignal(
            name="property_changed",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="value", type="Variant"),
                SignalArgument(name="field", type="StringName"),
                SignalArgument(name="changing", type="bool"),
            ),
        ),
        "property_checked": GodotSignal(
            name="property_checked",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="checked", type="bool"),
            ),
        ),
        "property_deleted": GodotSignal(
            name="property_deleted",
            arguments=(SignalArgument(name="property", type="StringName"),),
        ),
        "property_favorited": GodotSignal(
            name="property_favorited",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="favorited", type="bool"),
            ),
        ),
        "property_keyed": GodotSignal(
            name="property_keyed",
            arguments=(SignalArgument(name="property", type="StringName"),),
        ),
        "property_keyed_with_value": GodotSignal(
            name="property_keyed_with_value",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="value", type="Variant"),
            ),
        ),
        "property_overridden": GodotSignal(name="property_overridden"),
        "property_pinned": GodotSignal(
            name="property_pinned",
            arguments=(
                SignalArgument(name="property", type="StringName"),
                SignalArgument(name="pinned", type="bool"),
            ),
        ),
        "resource_selected": GodotSignal(
            name="resource_selected",
            arguments=(
                SignalArgument(name="path", type="String"),
                SignalArgument(name="resource", type="Resource"),
            ),
        ),
        "selected": GodotSignal(
            name="selected",
            arguments=(
                SignalArgument(name="path", type="String"),
                SignalArgument(name="focusable_idx", type="int"),
            ),
        ),
    },
    "EditorResourcePicker": {
        "resource_changed": GodotSignal(
            name="resource_changed",
            arguments=(SignalArgument(name="resource", type="Resource"),),
        ),
        "resource_selected": GodotSignal(
            name="resource_selected",
            arguments=(
                SignalArgument(name="resource", type="Resource"),
                SignalArgument(name="inspect", type="bool"),
            ),
        ),
    },
    "EditorResourcePreview": {
        "preview_invalidated": GodotSignal(
            name="preview_invalidated",
            arguments=(SignalArgument(name="path", type="String"),),
        ),
    },
    "EditorSelection": {
        "selection_changed": GodotSignal(name="selection_changed"),
    },
    "EditorSettings": {
        "settings_changed": GodotSignal(name="settings_changed"),
    },
    "EditorSpinSlider": {
        "grabbed": GodotSignal(name="grabbed"),
        "ungrabbed": GodotSignal(name="ungrabbed"),
        "updown_pressed": GodotSignal(name="updown_pressed"),
        "value_focus_entered": GodotSignal(name="value_focus_entered"),
        "value_focus_exited": GodotSignal(name="value_focus_exited"),
    },
    "EditorUndoRedoManager": {
        "history_changed": GodotSignal(name="history_changed"),
        "version_changed": GodotSignal(name="version_changed"),
    },
    "FileDialog": {
        "dir_selected": GodotSignal(
            name="dir_selected", arguments=(SignalArgument(name="dir", type="String"),)
        ),
        "file_selected": GodotSignal(
            name="file_selected",
            arguments=(SignalArgument(name="path", type="String"),),
        ),
        "filename_filter_changed": GodotSignal(
            name="filename_filter_changed",
            arguments=(SignalArgument(name="filter", type="String"),),
        ),
        "files_selected": GodotSignal(
            name="files_selected",
            arguments=(SignalArgument(name="paths", type="PackedStringArray"),),
        ),
    },
    "FileSystemDock": {
        "display_mode_changed": GodotSignal(name="display_mode_changed"),
        "file_removed": GodotSignal(
            name="file_removed", arguments=(SignalArgument(name="file", type="String"),)
        ),
        "files_moved": GodotSignal(
            name="files_moved",
            arguments=(
                SignalArgument(name="old_file", type="String"),
                SignalArgument(name="new_file", type="String"),
            ),
        ),
        "folder_color_changed": GodotSignal(name="folder_color_changed"),
        "folder_moved": GodotSignal(
            name="folder_moved",
            arguments=(
                SignalArgument(name="old_folder", type="String"),
                SignalArgument(name="new_folder", type="String"),
            ),
        ),
        "folder_removed": GodotSignal(
            name="folder_removed",
            arguments=(SignalArgument(name="folder", type="String"),),
        ),
        "inherit": GodotSignal(
            name="inherit", arguments=(SignalArgument(name="file", type="String"),)
        ),
        "instantiate": GodotSignal(
            name="instantiate",
            arguments=(SignalArgument(name="files", type="PackedStringArray"),),
        ),
        "resource_removed": GodotSignal(
            name="resource_removed",
            arguments=(SignalArgument(name="resource", type="Resource"),),
        ),
    },
    "FoldableContainer": {
        "folding_changed": GodotSignal(
            name="folding_changed",
            arguments=(SignalArgument(name="is_folded", type="bool"),),
        ),
    },
    "FoldableGroup": {
        "expanded": GodotSignal(
            name="expanded",
            arguments=(SignalArgument(name="container", type="FoldableContainer"),),
        ),
    },
    "GDExtensionManager": {
        "extension_loaded": GodotSignal(
            name="extension_loaded",
            arguments=(SignalArgument(name="extension", type="GDExtension"),),
        ),
        "extension_unloading": GodotSignal(
            name="extension_unloading",
            arguments=(SignalArgument(name="extension", type="GDExtension"),),
        ),
        "extensions_reloaded": GodotSignal(name="extensions_reloaded"),
    },
    "GPUParticles2D": {
        "finished": GodotSignal(name="finished"),
    },
    "GPUParticles3D": {
        "finished": GodotSignal(name="finished"),
    },
    "GraphEdit": {
        "begin_node_move": GodotSignal(name="begin_node_move"),
        "connection_drag_ended": GodotSignal(name="connection_drag_ended"),
        "connection_drag_started": GodotSignal(
            name="connection_drag_started",
            arguments=(
                SignalArgument(name="from_node", type="StringName"),
                SignalArgument(name="from_port", type="int"),
                SignalArgument(name="is_output", type="bool"),
            ),
        ),
        "connection_from_empty": GodotSignal(
            name="connection_from_empty",
            arguments=(
                SignalArgument(name="to_node", type="StringName"),
                SignalArgument(name="to_port", type="int"),
                SignalArgument(name="release_position", type="Vector2"),
            ),
        ),
        "connection_request": GodotSignal(
            name="connection_request",
            arguments=(
                SignalArgument(name="from_node", type="StringName"),
                SignalArgument(name="from_port", type="int"),
                SignalArgument(name="to_node", type="StringName"),
                SignalArgument(name="to_port", type="int"),
            ),
        ),
        "connection_to_empty": GodotSignal(
            name="connection_to_empty",
            arguments=(
                SignalArgument(name="from_node", type="StringName"),
                SignalArgument(name="from_port", type="int"),
                SignalArgument(name="release_position", type="Vector2"),
            ),
        ),
        "copy_nodes_request": GodotSignal(name="copy_nodes_request"),
        "cut_nodes_request": GodotSignal(name="cut_nodes_request"),
        "delete_nodes_request": GodotSignal(
            name="delete_nodes_request",
            arguments=(SignalArgument(name="nodes", type="typedarray::StringName"),),
        ),
        "disconnection_request": GodotSignal(
            name="disconnection_request",
            arguments=(
                SignalArgument(name="from_node", type="StringName"),
                SignalArgument(name="from_port", type="int"),
                SignalArgument(name="to_node", type="StringName"),
                SignalArgument(name="to_port", type="int"),
            ),
        ),
        "duplicate_nodes_request": GodotSignal(name="duplicate_nodes_request"),
        "end_node_move": GodotSignal(name="end_node_move"),
        "frame_rect_changed": GodotSignal(
            name="frame_rect_changed",
            arguments=(
                SignalArgument(name="frame", type="GraphFrame"),
                SignalArgument(name="new_rect", type="Rect2"),
            ),
        ),
        "graph_elements_linked_to_frame_request": GodotSignal(
            name="graph_elements_linked_to_frame_request",
            arguments=(
                SignalArgument(name="elements", type="Array"),
                SignalArgument(name="frame", type="StringName"),
            ),
        ),
        "node_deselected": GodotSignal(
            name="node_deselected",
            arguments=(SignalArgument(name="node", type="Node"),),
        ),
        "node_selected": GodotSignal(
            name="node_selected", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "paste_nodes_request": GodotSignal(name="paste_nodes_request"),
        "popup_request": GodotSignal(
            name="popup_request",
            arguments=(SignalArgument(name="at_position", type="Vector2"),),
        ),
        "scroll_offset_changed": GodotSignal(
            name="scroll_offset_changed",
            arguments=(SignalArgument(name="offset", type="Vector2"),),
        ),
    },
    "GraphElement": {
        "delete_request": GodotSignal(name="delete_request"),
        "dragged": GodotSignal(
            name="dragged",
            arguments=(
                SignalArgument(name="from", type="Vector2"),
                SignalArgument(name="to", type="Vector2"),
            ),
        ),
        "node_deselected": GodotSignal(name="node_deselected"),
        "node_selected": GodotSignal(name="node_selected"),
        "position_offset_changed": GodotSignal(name="position_offset_changed"),
        "raise_request": GodotSignal(name="raise_request"),
        "resize_end": GodotSignal(
            name="resize_end",
            arguments=(SignalArgument(name="new_size", type="Vector2"),),
        ),
        "resize_request": GodotSignal(
            name="resize_request",
            arguments=(SignalArgument(name="new_size", type="Vector2"),),
        ),
    },
    "GraphFrame": {
        "autoshrink_changed": GodotSignal(name="autoshrink_changed"),
    },
    "GraphNode": {
        "slot_sizes_changed": GodotSignal(name="slot_sizes_changed"),
        "slot_updated": GodotSignal(
            name="slot_updated",
            arguments=(SignalArgument(name="slot_index", type="int"),),
        ),
    },
    "GridMap": {
        "cell_size_changed": GodotSignal(
            name="cell_size_changed",
            arguments=(SignalArgument(name="cell_size", type="Vector3"),),
        ),
        "changed": GodotSignal(name="changed"),
    },
    "HTTPRequest": {
        "request_completed": GodotSignal(
            name="request_completed",
            arguments=(
                SignalArgument(name="result", type="int"),
                SignalArgument(name="response_code", type="int"),
                SignalArgument(name="headers", type="PackedStringArray"),
                SignalArgument(name="body", type="PackedByteArray"),
            ),
        ),
    },
    "Input": {
        "joy_connection_changed": GodotSignal(
            name="joy_connection_changed",
            arguments=(
                SignalArgument(name="device", type="int"),
                SignalArgument(name="connected", type="bool"),
            ),
        ),
    },
    "ItemList": {
        "empty_clicked": GodotSignal(
            name="empty_clicked",
            arguments=(
                SignalArgument(name="at_position", type="Vector2"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "item_activated": GodotSignal(
            name="item_activated", arguments=(SignalArgument(name="index", type="int"),)
        ),
        "item_clicked": GodotSignal(
            name="item_clicked",
            arguments=(
                SignalArgument(name="index", type="int"),
                SignalArgument(name="at_position", type="Vector2"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "item_selected": GodotSignal(
            name="item_selected", arguments=(SignalArgument(name="index", type="int"),)
        ),
        "multi_selected": GodotSignal(
            name="multi_selected",
            arguments=(
                SignalArgument(name="index", type="int"),
                SignalArgument(name="selected", type="bool"),
            ),
        ),
    },
    "JavaScriptBridge": {
        "pwa_update_available": GodotSignal(name="pwa_update_available"),
    },
    "LineEdit": {
        "editing_toggled": GodotSignal(
            name="editing_toggled",
            arguments=(SignalArgument(name="toggled_on", type="bool"),),
        ),
        "text_change_rejected": GodotSignal(
            name="text_change_rejected",
            arguments=(SignalArgument(name="rejected_substring", type="String"),),
        ),
        "text_changed": GodotSignal(
            name="text_changed",
            arguments=(SignalArgument(name="new_text", type="String"),),
        ),
        "text_submitted": GodotSignal(
            name="text_submitted",
            arguments=(SignalArgument(name="new_text", type="String"),),
        ),
    },
    "MainLoop": {
        "on_request_permissions_result": GodotSignal(
            name="on_request_permissions_result",
            arguments=(
                SignalArgument(name="permission", type="String"),
                SignalArgument(name="granted", type="bool"),
            ),
        ),
    },
    "MenuButton": {
        "about_to_popup": GodotSignal(name="about_to_popup"),
    },
    "MeshInstance2D": {
        "texture_changed": GodotSignal(name="texture_changed"),
    },
    "MultiMeshInstance2D": {
        "texture_changed": GodotSignal(name="texture_changed"),
    },
    "MultiplayerAPI": {
        "connected_to_server": GodotSignal(name="connected_to_server"),
        "connection_failed": GodotSignal(name="connection_failed"),
        "peer_connected": GodotSignal(
            name="peer_connected", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "peer_disconnected": GodotSignal(
            name="peer_disconnected", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "server_disconnected": GodotSignal(name="server_disconnected"),
    },
    "MultiplayerPeer": {
        "peer_connected": GodotSignal(
            name="peer_connected", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "peer_disconnected": GodotSignal(
            name="peer_disconnected", arguments=(SignalArgument(name="id", type="int"),)
        ),
    },
    "MultiplayerSpawner": {
        "despawned": GodotSignal(
            name="despawned", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "spawned": GodotSignal(
            name="spawned", arguments=(SignalArgument(name="node", type="Node"),)
        ),
    },
    "MultiplayerSynchronizer": {
        "delta_synchronized": GodotSignal(name="delta_synchronized"),
        "synchronized": GodotSignal(name="synchronized"),
        "visibility_changed": GodotSignal(
            name="visibility_changed",
            arguments=(SignalArgument(name="for_peer", type="int"),),
        ),
    },
    "NavigationAgent2D": {
        "link_reached": GodotSignal(
            name="link_reached",
            arguments=(SignalArgument(name="details", type="Dictionary"),),
        ),
        "navigation_finished": GodotSignal(name="navigation_finished"),
        "path_changed": GodotSignal(name="path_changed"),
        "target_reached": GodotSignal(name="target_reached"),
        "velocity_computed": GodotSignal(
            name="velocity_computed",
            arguments=(SignalArgument(name="safe_velocity", type="Vector2"),),
        ),
        "waypoint_reached": GodotSignal(
            name="waypoint_reached",
            arguments=(SignalArgument(name="details", type="Dictionary"),),
        ),
    },
    "NavigationAgent3D": {
        "link_reached": GodotSignal(
            name="link_reached",
            arguments=(SignalArgument(name="details", type="Dictionary"),),
        ),
        "navigation_finished": GodotSignal(name="navigation_finished"),
        "path_changed": GodotSignal(name="path_changed"),
        "target_reached": GodotSignal(name="target_reached"),
        "velocity_computed": GodotSignal(
            name="velocity_computed",
            arguments=(SignalArgument(name="safe_velocity", type="Vector3"),),
        ),
        "waypoint_reached": GodotSignal(
            name="waypoint_reached",
            arguments=(SignalArgument(name="details", type="Dictionary"),),
        ),
    },
    "NavigationRegion2D": {
        "bake_finished": GodotSignal(name="bake_finished"),
        "navigation_polygon_changed": GodotSignal(name="navigation_polygon_changed"),
    },
    "NavigationRegion3D": {
        "bake_finished": GodotSignal(name="bake_finished"),
        "navigation_mesh_changed": GodotSignal(name="navigation_mesh_changed"),
    },
    "NavigationServer2D": {
        "avoidance_debug_changed": GodotSignal(name="avoidance_debug_changed"),
        "map_changed": GodotSignal(
            name="map_changed", arguments=(SignalArgument(name="map", type="RID"),)
        ),
        "navigation_debug_changed": GodotSignal(name="navigation_debug_changed"),
    },
    "NavigationServer3D": {
        "avoidance_debug_changed": GodotSignal(name="avoidance_debug_changed"),
        "map_changed": GodotSignal(
            name="map_changed", arguments=(SignalArgument(name="map", type="RID"),)
        ),
        "navigation_debug_changed": GodotSignal(name="navigation_debug_changed"),
    },
    "NinePatchRect": {
        "texture_changed": GodotSignal(name="texture_changed"),
    },
    "Node": {
        "child_entered_tree": GodotSignal(
            name="child_entered_tree",
            arguments=(SignalArgument(name="node", type="Node"),),
        ),
        "child_exiting_tree": GodotSignal(
            name="child_exiting_tree",
            arguments=(SignalArgument(name="node", type="Node"),),
        ),
        "child_order_changed": GodotSignal(name="child_order_changed"),
        "editor_description_changed": GodotSignal(
            name="editor_description_changed",
            arguments=(SignalArgument(name="node", type="Node"),),
        ),
        "editor_state_changed": GodotSignal(name="editor_state_changed"),
        "ready": GodotSignal(name="ready"),
        "renamed": GodotSignal(name="renamed"),
        "replacing_by": GodotSignal(
            name="replacing_by", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "tree_entered": GodotSignal(name="tree_entered"),
        "tree_exited": GodotSignal(name="tree_exited"),
        "tree_exiting": GodotSignal(name="tree_exiting"),
    },
    "Node3D": {
        "visibility_changed": GodotSignal(name="visibility_changed"),
    },
    "Object": {
        "property_list_changed": GodotSignal(name="property_list_changed"),
        "script_changed": GodotSignal(name="script_changed"),
    },
    "OpenXRBindingModifierEditor": {
        "binding_modifier_removed": GodotSignal(
            name="binding_modifier_removed",
            arguments=(SignalArgument(name="binding_modifier_editor", type="Object"),),
        ),
    },
    "OpenXRFutureResult": {
        "completed": GodotSignal(
            name="completed",
            arguments=(SignalArgument(name="result", type="OpenXRFutureResult"),),
        ),
    },
    "OpenXRInterface": {
        "cpu_level_changed": GodotSignal(
            name="cpu_level_changed",
            arguments=(
                SignalArgument(name="sub_domain", type="int"),
                SignalArgument(name="from_level", type="int"),
                SignalArgument(name="to_level", type="int"),
            ),
        ),
        "gpu_level_changed": GodotSignal(
            name="gpu_level_changed",
            arguments=(
                SignalArgument(name="sub_domain", type="int"),
                SignalArgument(name="from_level", type="int"),
                SignalArgument(name="to_level", type="int"),
            ),
        ),
        "instance_exiting": GodotSignal(name="instance_exiting"),
        "pose_recentered": GodotSignal(name="pose_recentered"),
        "refresh_rate_changed": GodotSignal(
            name="refresh_rate_changed",
            arguments=(SignalArgument(name="refresh_rate", type="float"),),
        ),
        "session_begun": GodotSignal(name="session_begun"),
        "session_focussed": GodotSignal(name="session_focussed"),
        "session_loss_pending": GodotSignal(name="session_loss_pending"),
        "session_stopping": GodotSignal(name="session_stopping"),
        "session_synchronized": GodotSignal(name="session_synchronized"),
        "session_visible": GodotSignal(name="session_visible"),
    },
    "OpenXRRenderModel": {
        "render_model_top_level_path_changed": GodotSignal(
            name="render_model_top_level_path_changed"
        ),
    },
    "OpenXRRenderModelExtension": {
        "render_model_added": GodotSignal(
            name="render_model_added",
            arguments=(SignalArgument(name="render_model", type="RID"),),
        ),
        "render_model_removed": GodotSignal(
            name="render_model_removed",
            arguments=(SignalArgument(name="render_model", type="RID"),),
        ),
        "render_model_top_level_path_changed": GodotSignal(
            name="render_model_top_level_path_changed",
            arguments=(SignalArgument(name="render_model", type="RID"),),
        ),
    },
    "OpenXRRenderModelManager": {
        "render_model_added": GodotSignal(
            name="render_model_added",
            arguments=(SignalArgument(name="render_model", type="OpenXRRenderModel"),),
        ),
        "render_model_removed": GodotSignal(
            name="render_model_removed",
            arguments=(SignalArgument(name="render_model", type="OpenXRRenderModel"),),
        ),
    },
    "OptionButton": {
        "item_focused": GodotSignal(
            name="item_focused", arguments=(SignalArgument(name="index", type="int"),)
        ),
        "item_selected": GodotSignal(
            name="item_selected", arguments=(SignalArgument(name="index", type="int"),)
        ),
    },
    "ParticleProcessMaterial": {
        "emission_shape_changed": GodotSignal(name="emission_shape_changed"),
    },
    "Path3D": {
        "curve_changed": GodotSignal(name="curve_changed"),
        "debug_color_changed": GodotSignal(name="debug_color_changed"),
    },
    "Popup": {
        "popup_hide": GodotSignal(name="popup_hide"),
    },
    "PopupMenu": {
        "id_focused": GodotSignal(
            name="id_focused", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "id_pressed": GodotSignal(
            name="id_pressed", arguments=(SignalArgument(name="id", type="int"),)
        ),
        "index_pressed": GodotSignal(
            name="index_pressed", arguments=(SignalArgument(name="index", type="int"),)
        ),
        "menu_changed": GodotSignal(name="menu_changed"),
    },
    "ProjectSettings": {
        "settings_changed": GodotSignal(name="settings_changed"),
    },
    "Range": {
        "changed": GodotSignal(name="changed"),
        "value_changed": GodotSignal(
            name="value_changed",
            arguments=(SignalArgument(name="value", type="float"),),
        ),
    },
    "RenderingServer": {
        "frame_post_draw": GodotSignal(name="frame_post_draw"),
        "frame_pre_draw": GodotSignal(name="frame_pre_draw"),
    },
    "Resource": {
        "changed": GodotSignal(name="changed"),
        "setup_local_to_scene_requested": GodotSignal(
            name="setup_local_to_scene_requested"
        ),
    },
    "RichTextLabel": {
        "finished": GodotSignal(name="finished"),
        "meta_clicked": GodotSignal(
            name="meta_clicked",
            arguments=(SignalArgument(name="meta", type="Variant"),),
        ),
        "meta_hover_ended": GodotSignal(
            name="meta_hover_ended",
            arguments=(SignalArgument(name="meta", type="Variant"),),
        ),
        "meta_hover_started": GodotSignal(
            name="meta_hover_started",
            arguments=(SignalArgument(name="meta", type="Variant"),),
        ),
    },
    "RigidBody2D": {
        "body_entered": GodotSignal(
            name="body_entered", arguments=(SignalArgument(name="body", type="Node"),)
        ),
        "body_exited": GodotSignal(
            name="body_exited", arguments=(SignalArgument(name="body", type="Node"),)
        ),
        "body_shape_entered": GodotSignal(
            name="body_shape_entered",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_shape_exited": GodotSignal(
            name="body_shape_exited",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "sleeping_state_changed": GodotSignal(name="sleeping_state_changed"),
    },
    "RigidBody3D": {
        "body_entered": GodotSignal(
            name="body_entered", arguments=(SignalArgument(name="body", type="Node"),)
        ),
        "body_exited": GodotSignal(
            name="body_exited", arguments=(SignalArgument(name="body", type="Node"),)
        ),
        "body_shape_entered": GodotSignal(
            name="body_shape_entered",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "body_shape_exited": GodotSignal(
            name="body_shape_exited",
            arguments=(
                SignalArgument(name="body_rid", type="RID"),
                SignalArgument(name="body", type="Node"),
                SignalArgument(name="body_shape_index", type="int"),
                SignalArgument(name="local_shape_index", type="int"),
            ),
        ),
        "sleeping_state_changed": GodotSignal(name="sleeping_state_changed"),
    },
    "SceneMultiplayer": {
        "peer_authenticating": GodotSignal(
            name="peer_authenticating",
            arguments=(SignalArgument(name="id", type="int"),),
        ),
        "peer_authentication_failed": GodotSignal(
            name="peer_authentication_failed",
            arguments=(SignalArgument(name="id", type="int"),),
        ),
        "peer_packet": GodotSignal(
            name="peer_packet",
            arguments=(
                SignalArgument(name="id", type="int"),
                SignalArgument(name="packet", type="PackedByteArray"),
            ),
        ),
    },
    "SceneTree": {
        "node_added": GodotSignal(
            name="node_added", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "node_configuration_warning_changed": GodotSignal(
            name="node_configuration_warning_changed",
            arguments=(SignalArgument(name="node", type="Node"),),
        ),
        "node_removed": GodotSignal(
            name="node_removed", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "node_renamed": GodotSignal(
            name="node_renamed", arguments=(SignalArgument(name="node", type="Node"),)
        ),
        "physics_frame": GodotSignal(name="physics_frame"),
        "process_frame": GodotSignal(name="process_frame"),
        "scene_changed": GodotSignal(name="scene_changed"),
        "tree_changed": GodotSignal(name="tree_changed"),
        "tree_process_mode_changed": GodotSignal(name="tree_process_mode_changed"),
    },
    "SceneTreeTimer": {
        "timeout": GodotSignal(name="timeout"),
    },
    "ScriptCreateDialog": {
        "script_created": GodotSignal(
            name="script_created",
            arguments=(SignalArgument(name="script", type="Script"),),
        ),
    },
    "ScriptEditor": {
        "editor_script_changed": GodotSignal(
            name="editor_script_changed",
            arguments=(SignalArgument(name="script", type="Script"),),
        ),
        "script_close": GodotSignal(
            name="script_close",
            arguments=(SignalArgument(name="script", type="Script"),),
        ),
    },
    "ScriptEditorBase": {
        "edited_script_changed": GodotSignal(name="edited_script_changed"),
        "go_to_help": GodotSignal(
            name="go_to_help", arguments=(SignalArgument(name="what", type="String"),)
        ),
        "go_to_method": GodotSignal(
            name="go_to_method",
            arguments=(
                SignalArgument(name="script", type="Object"),
                SignalArgument(name="method", type="String"),
            ),
        ),
        "name_changed": GodotSignal(name="name_changed"),
        "replace_in_files_requested": GodotSignal(
            name="replace_in_files_requested",
            arguments=(SignalArgument(name="text", type="String"),),
        ),
        "request_help": GodotSignal(
            name="request_help",
            arguments=(SignalArgument(name="topic", type="String"),),
        ),
        "request_open_script_at_line": GodotSignal(
            name="request_open_script_at_line",
            arguments=(
                SignalArgument(name="script", type="Object"),
                SignalArgument(name="line", type="int"),
            ),
        ),
        "request_save_history": GodotSignal(name="request_save_history"),
        "request_save_previous_state": GodotSignal(
            name="request_save_previous_state",
            arguments=(SignalArgument(name="state", type="Dictionary"),),
        ),
        "search_in_files_requested": GodotSignal(
            name="search_in_files_requested",
            arguments=(SignalArgument(name="text", type="String"),),
        ),
    },
    "ScrollBar": {
        "scrolling": GodotSignal(name="scrolling"),
    },
    "ScrollContainer": {
        "scroll_ended": GodotSignal(name="scroll_ended"),
        "scroll_started": GodotSignal(name="scroll_started"),
    },
    "Skeleton2D": {
        "bone_setup_changed": GodotSignal(name="bone_setup_changed"),
    },
    "Skeleton3D": {
        "bone_enabled_changed": GodotSignal(
            name="bone_enabled_changed",
            arguments=(SignalArgument(name="bone_idx", type="int"),),
        ),
        "bone_list_changed": GodotSignal(name="bone_list_changed"),
        "pose_updated": GodotSignal(name="pose_updated"),
        "rest_updated": GodotSignal(name="rest_updated"),
        "show_rest_only_changed": GodotSignal(name="show_rest_only_changed"),
        "skeleton_updated": GodotSignal(name="skeleton_updated"),
    },
    "SkeletonModifier3D": {
        "modification_processed": GodotSignal(name="modification_processed"),
    },
    "SkeletonProfile": {
        "profile_updated": GodotSignal(name="profile_updated"),
    },
    "Slider": {
        "drag_ended": GodotSignal(
            name="drag_ended",
            arguments=(SignalArgument(name="value_changed", type="bool"),),
        ),
        "drag_started": GodotSignal(name="drag_started"),
    },
    "SplitContainer": {
        "drag_ended": GodotSignal(name="drag_ended"),
        "drag_started": GodotSignal(name="drag_started"),
        "dragged": GodotSignal(
            name="dragged", arguments=(SignalArgument(name="offset", type="int"),)
        ),
    },
    "Sprite2D": {
        "frame_changed": GodotSignal(name="frame_changed"),
        "texture_changed": GodotSignal(name="texture_changed"),
    },
    "Sprite3D": {
        "frame_changed": GodotSignal(name="frame_changed"),
        "texture_changed": GodotSignal(name="texture_changed"),
    },
    "StatusIndicator": {
        "pressed": GodotSignal(
            name="pressed",
            arguments=(
                SignalArgument(name="mouse_button", type="int"),
                SignalArgument(name="mouse_position", type="Vector2i"),
            ),
        ),
    },
    "TabBar": {
        "active_tab_rearranged": GodotSignal(
            name="active_tab_rearranged",
            arguments=(SignalArgument(name="idx_to", type="int"),),
        ),
        "tab_button_pressed": GodotSignal(
            name="tab_button_pressed",
            arguments=(SignalArgument(name="tab", type="int"),),
        ),
        "tab_changed": GodotSignal(
            name="tab_changed", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_clicked": GodotSignal(
            name="tab_clicked", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_close_pressed": GodotSignal(
            name="tab_close_pressed",
            arguments=(SignalArgument(name="tab", type="int"),),
        ),
        "tab_hovered": GodotSignal(
            name="tab_hovered", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_rmb_clicked": GodotSignal(
            name="tab_rmb_clicked", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_selected": GodotSignal(
            name="tab_selected", arguments=(SignalArgument(name="tab", type="int"),)
        ),
    },
    "TabContainer": {
        "active_tab_rearranged": GodotSignal(
            name="active_tab_rearranged",
            arguments=(SignalArgument(name="idx_to", type="int"),),
        ),
        "pre_popup_pressed": GodotSignal(name="pre_popup_pressed"),
        "tab_button_pressed": GodotSignal(
            name="tab_button_pressed",
            arguments=(SignalArgument(name="tab", type="int"),),
        ),
        "tab_changed": GodotSignal(
            name="tab_changed", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_clicked": GodotSignal(
            name="tab_clicked", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_hovered": GodotSignal(
            name="tab_hovered", arguments=(SignalArgument(name="tab", type="int"),)
        ),
        "tab_selected": GodotSignal(
            name="tab_selected", arguments=(SignalArgument(name="tab", type="int"),)
        ),
    },
    "TextEdit": {
        "caret_changed": GodotSignal(name="caret_changed"),
        "gutter_added": GodotSignal(name="gutter_added"),
        "gutter_clicked": GodotSignal(
            name="gutter_clicked",
            arguments=(
                SignalArgument(name="line", type="int"),
                SignalArgument(name="gutter", type="int"),
            ),
        ),
        "gutter_removed": GodotSignal(name="gutter_removed"),
        "lines_edited_from": GodotSignal(
            name="lines_edited_from",
            arguments=(
                SignalArgument(name="from_line", type="int"),
                SignalArgument(name="to_line", type="int"),
            ),
        ),
        "text_changed": GodotSignal(name="text_changed"),
        "text_set": GodotSignal(name="text_set"),
    },
    "TextServerManager": {
        "interface_added": GodotSignal(
            name="interface_added",
            arguments=(SignalArgument(name="interface_name", type="StringName"),),
        ),
        "interface_removed": GodotSignal(
            name="interface_removed",
            arguments=(SignalArgument(name="interface_name", type="StringName"),),
        ),
    },
    "ThemeDB": {
        "fallback_changed": GodotSignal(name="fallback_changed"),
    },
    "TileData": {
        "changed": GodotSignal(name="changed"),
    },
    "TileMap": {
        "changed": GodotSignal(name="changed"),
    },
    "TileMapLayer": {
        "changed": GodotSignal(name="changed"),
    },
    "Timer": {
        "timeout": GodotSignal(name="timeout"),
    },
    "TouchScreenButton": {
        "pressed": GodotSignal(name="pressed"),
        "released": GodotSignal(name="released"),
    },
    "Tree": {
        "button_clicked": GodotSignal(
            name="button_clicked",
            arguments=(
                SignalArgument(name="item", type="TreeItem"),
                SignalArgument(name="column", type="int"),
                SignalArgument(name="id", type="int"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "cell_selected": GodotSignal(name="cell_selected"),
        "check_propagated_to_item": GodotSignal(
            name="check_propagated_to_item",
            arguments=(
                SignalArgument(name="item", type="TreeItem"),
                SignalArgument(name="column", type="int"),
            ),
        ),
        "column_title_clicked": GodotSignal(
            name="column_title_clicked",
            arguments=(
                SignalArgument(name="column", type="int"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "custom_item_clicked": GodotSignal(
            name="custom_item_clicked",
            arguments=(SignalArgument(name="mouse_button_index", type="int"),),
        ),
        "custom_popup_edited": GodotSignal(
            name="custom_popup_edited",
            arguments=(SignalArgument(name="arrow_clicked", type="bool"),),
        ),
        "empty_clicked": GodotSignal(
            name="empty_clicked",
            arguments=(
                SignalArgument(name="click_position", type="Vector2"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "item_activated": GodotSignal(name="item_activated"),
        "item_collapsed": GodotSignal(
            name="item_collapsed",
            arguments=(SignalArgument(name="item", type="TreeItem"),),
        ),
        "item_edited": GodotSignal(name="item_edited"),
        "item_icon_double_clicked": GodotSignal(name="item_icon_double_clicked"),
        "item_mouse_selected": GodotSignal(
            name="item_mouse_selected",
            arguments=(
                SignalArgument(name="mouse_position", type="Vector2"),
                SignalArgument(name="mouse_button_index", type="int"),
            ),
        ),
        "item_selected": GodotSignal(name="item_selected"),
        "multi_selected": GodotSignal(
            name="multi_selected",
            arguments=(
                SignalArgument(name="item", type="TreeItem"),
                SignalArgument(name="column", type="int"),
                SignalArgument(name="selected", type="bool"),
            ),
        ),
        "nothing_selected": GodotSignal(name="nothing_selected"),
    },
    "Tween": {
        "finished": GodotSignal(name="finished"),
        "loop_finished": GodotSignal(
            name="loop_finished",
            arguments=(SignalArgument(name="loop_count", type="int"),),
        ),
        "step_finished": GodotSignal(
            name="step_finished", arguments=(SignalArgument(name="idx", type="int"),)
        ),
    },
    "Tweener": {
        "finished": GodotSignal(name="finished"),
    },
    "UndoRedo": {
        "version_changed": GodotSignal(name="version_changed"),
    },
    "VideoStreamPlayer": {
        "finished": GodotSignal(name="finished"),
    },
    "Viewport": {
        "gui_focus_changed": GodotSignal(
            name="gui_focus_changed",
            arguments=(SignalArgument(name="node", type="Control"),),
        ),
        "size_changed": GodotSignal(name="size_changed"),
    },
    "VisibleOnScreenNotifier2D": {
        "screen_entered": GodotSignal(name="screen_entered"),
        "screen_exited": GodotSignal(name="screen_exited"),
    },
    "VisibleOnScreenNotifier3D": {
        "screen_entered": GodotSignal(name="screen_entered"),
        "screen_exited": GodotSignal(name="screen_exited"),
    },
    "VisualShaderNodeInput": {
        "input_type_changed": GodotSignal(name="input_type_changed"),
    },
    "WebRTCPeerConnection": {
        "data_channel_received": GodotSignal(
            name="data_channel_received",
            arguments=(SignalArgument(name="channel", type="WebRTCDataChannel"),),
        ),
        "ice_candidate_created": GodotSignal(
            name="ice_candidate_created",
            arguments=(
                SignalArgument(name="media", type="String"),
                SignalArgument(name="index", type="int"),
                SignalArgument(name="name", type="String"),
            ),
        ),
        "session_description_created": GodotSignal(
            name="session_description_created",
            arguments=(
                SignalArgument(name="type", type="String"),
                SignalArgument(name="sdp", type="String"),
            ),
        ),
    },
    "WebXRInterface": {
        "display_refresh_rate_changed": GodotSignal(
            name="display_refresh_rate_changed"
        ),
        "reference_space_reset": GodotSignal(name="reference_space_reset"),
        "select": GodotSignal(
            name="select",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "selectend": GodotSignal(
            name="selectend",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "selectstart": GodotSignal(
            name="selectstart",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "session_ended": GodotSignal(name="session_ended"),
        "session_failed": GodotSignal(
            name="session_failed",
            arguments=(SignalArgument(name="message", type="String"),),
        ),
        "session_started": GodotSignal(name="session_started"),
        "session_supported": GodotSignal(
            name="session_supported",
            arguments=(
                SignalArgument(name="session_mode", type="String"),
                SignalArgument(name="supported", type="bool"),
            ),
        ),
        "squeeze": GodotSignal(
            name="squeeze",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "squeezeend": GodotSignal(
            name="squeezeend",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "squeezestart": GodotSignal(
            name="squeezestart",
            arguments=(SignalArgument(name="input_source_id", type="int"),),
        ),
        "visibility_state_changed": GodotSignal(name="visibility_state_changed"),
    },
    "Window": {
        "about_to_popup": GodotSignal(name="about_to_popup"),
        "close_requested": GodotSignal(name="close_requested"),
        "dpi_changed": GodotSignal(name="dpi_changed"),
        "files_dropped": GodotSignal(
            name="files_dropped",
            arguments=(SignalArgument(name="files", type="PackedStringArray"),),
        ),
        "focus_entered": GodotSignal(name="focus_entered"),
        "focus_exited": GodotSignal(name="focus_exited"),
        "go_back_requested": GodotSignal(name="go_back_requested"),
        "mouse_entered": GodotSignal(name="mouse_entered"),
        "mouse_exited": GodotSignal(name="mouse_exited"),
        "theme_changed": GodotSignal(name="theme_changed"),
        "title_changed": GodotSignal(name="title_changed"),
        "titlebar_changed": GodotSignal(name="titlebar_changed"),
        "visibility_changed": GodotSignal(name="visibility_changed"),
        "window_input": GodotSignal(
            name="window_input",
            arguments=(SignalArgument(name="event", type="InputEvent"),),
        ),
    },
    "XRController3D": {
        "button_pressed": GodotSignal(
            name="button_pressed",
            arguments=(SignalArgument(name="name", type="String"),),
        ),
        "button_released": GodotSignal(
            name="button_released",
            arguments=(SignalArgument(name="name", type="String"),),
        ),
        "input_float_changed": GodotSignal(
            name="input_float_changed",
            arguments=(
                SignalArgument(name="name", type="String"),
                SignalArgument(name="value", type="float"),
            ),
        ),
        "input_vector2_changed": GodotSignal(
            name="input_vector2_changed",
            arguments=(
                SignalArgument(name="name", type="String"),
                SignalArgument(name="value", type="Vector2"),
            ),
        ),
        "profile_changed": GodotSignal(
            name="profile_changed",
            arguments=(SignalArgument(name="role", type="String"),),
        ),
    },
    "XRInterface": {
        "play_area_changed": GodotSignal(
            name="play_area_changed",
            arguments=(SignalArgument(name="mode", type="int"),),
        ),
    },
    "XRNode3D": {
        "tracking_changed": GodotSignal(
            name="tracking_changed",
            arguments=(SignalArgument(name="tracking", type="bool"),),
        ),
    },
    "XRPositionalTracker": {
        "button_pressed": GodotSignal(
            name="button_pressed",
            arguments=(SignalArgument(name="name", type="String"),),
        ),
        "button_released": GodotSignal(
            name="button_released",
            arguments=(SignalArgument(name="name", type="String"),),
        ),
        "input_float_changed": GodotSignal(
            name="input_float_changed",
            arguments=(
                SignalArgument(name="name", type="String"),
                SignalArgument(name="value", type="float"),
            ),
        ),
        "input_vector2_changed": GodotSignal(
            name="input_vector2_changed",
            arguments=(
                SignalArgument(name="name", type="String"),
                SignalArgument(name="vector", type="Vector2"),
            ),
        ),
        "pose_changed": GodotSignal(
            name="pose_changed", arguments=(SignalArgument(name="pose", type="XRPose"),)
        ),
        "pose_lost_tracking": GodotSignal(
            name="pose_lost_tracking",
            arguments=(SignalArgument(name="pose", type="XRPose"),),
        ),
        "profile_changed": GodotSignal(
            name="profile_changed",
            arguments=(SignalArgument(name="role", type="String"),),
        ),
    },
    "XRServer": {
        "interface_added": GodotSignal(
            name="interface_added",
            arguments=(SignalArgument(name="interface_name", type="StringName"),),
        ),
        "interface_removed": GodotSignal(
            name="interface_removed",
            arguments=(SignalArgument(name="interface_name", type="StringName"),),
        ),
        "reference_frame_changed": GodotSignal(name="reference_frame_changed"),
        "tracker_added": GodotSignal(
            name="tracker_added",
            arguments=(
                SignalArgument(name="tracker_name", type="StringName"),
                SignalArgument(name="type", type="int"),
            ),
        ),
        "tracker_removed": GodotSignal(
            name="tracker_removed",
            arguments=(
                SignalArgument(name="tracker_name", type="StringName"),
                SignalArgument(name="type", type="int"),
            ),
        ),
        "tracker_updated": GodotSignal(
            name="tracker_updated",
            arguments=(
                SignalArgument(name="tracker_name", type="StringName"),
                SignalArgument(name="type", type="int"),
            ),
        ),
    },
}
